local M = {}

function M.setup(configColors, configStyle)
    local newpaper = configColors
    local style    = configStyle

    return {
        -- ["@_env"]                 = { link = "@conceal" },
        ["@_frac_name"]           = { link = "@function.math.operator.latex" },
        ["@_func_name"]           = { link = "@function.math.operator.latex" },
        -- ["@_line"]                = { link = "@conceal" },
        ["@abs_name"]             = { link = "@function.math.operator.latex" },
        ["@close_paren"]          = { link = "@punctuation.bracket.math.sub.latex" },
        ["@cmd"]                  = { link = "@function.latex" },
        ["@cmd_escape"]           = { link = "@character.special.latex" },
        ["@comma"]                = { link = "@punctuation.delimiter.latex" },
        ["@conceal_dollar"]       = { link = "@markup.math.delim" },
        -- ["@content"]              = { link = "@conceal" },
        -- ["@first_letter"]         = { link = "@conceal" },
        -- ["@font_letter"]          = { link = "@conceal" },
        ["@font_digit"]           = { link = "@number.latex" },
        ["@frac"]                 = { link = "@function.math.operator.latex" },
        ["@func"]                 = { link = "@function.latex" },
        ["@func_name"]            = { link = "@function.math.operator.latex" },
        ["@left_1"]               = { link = "@punctuation.bracket.math.latex" },
        ["@left_2"]               = { link = "@punctuation.bracket.math.latex" },
        ["@left_brace"]           = { link = "@punctuation.delimiter.latex" },
        -- ["@left_content"]         = { link = "@conceal" },
        ["@left_paren"]           = { link = "@function.math.markup.latex" },
        ["@left_paren_cmd"]       = { link = "@punctuation.bracket.math.sub.latex" },
        ["@open_paren"]           = { link = "@punctuation.bracket.math.sub.latex" },
        -- ["@punctuation"]          = { link = "@conceal" },
        ["@punctuation.comma"]    = { link = "@function.math.operator.latex" },
        ["@right_1"]              = { link = "@operator.math.slash.latex" },
        ["@right_2"]              = { link = "@punctuation.bracket.math.latex" },
        ["@right_brace"]          = { link = "@punctuation.delimiter.latex" },
        -- ["@right_content"]        = { link = "@conceal" },
        ["@right_paren"]          = { link = "@function.math.markup.latex" },
        ["@right_paren_cmd"]      = { link = "@punctuation.bracket.math.sub.latex" },
        -- ["@second_letter"]        = { link = "@conceal" },
        ["@sub_digit"]            = { fg = newpaper.tex_red },
        ["@sub_letter"]           = { fg = newpaper.tex_red, style = style.italic },
        ["@sub_object"]           = { link = "@sub_letter" },
        -- ["@sub_string"]           = { link = "@string.typst" },
        ["@sub_symbol"]           = { link = "@operator.math.sub.latex" },
        ["@sup_digit"]            = { link = "@sub_digit" },
        ["@sup_letter"]           = { link = "@sub_letter" },
        ["@sup_object"]           = { link = "@sub_letter" },
        -- ["@sup_string"]           = { link = "@string.typst" },
        ["@sup_symbol"]           = { link = "@operator.math.sub.latex" },
        ["@symbol"]               = { link = "@operator.math.typst" },
        ["@tex_font_name"]        = { link = "@function.math.markup.latex" },
        ["@tex_greek"]            = { link = "@function.math.greek.latex" },
        -- ["@tex_math_command"]     = { link = "@conceal" },

        ["@typ_font_name"]        = { link = "@function.latex" },
        ["@typ_greek_symbol"]     = { link = "@function.call.greek.typst" },
        ["@typ_inline_ampersand"] = { link = "@function.call.delim.typst" },
        ["@typ_inline_asterisk"]  = { link = "@markup.quote.marker" },
        ["@typ_inline_dollar"]    = { link = "@markup.math.delim" },
        ["@typ_inline_quote"]     = { link = "@markup.quote.marker" },
        ["@typ_math_delim"]       = { link = "@function.call.delim.typst" },
        ["@typ_math_font"]        = { link = "@function.math.markup.latex" },
        -- ["@typ_math_symbol"]      = { link = "@conceal" },
        ["@typ_symbol"]           = { link = "@character.special" },
        ["@typ_phy_symbol"]       = { link = "@character.special.ligatures.typst" },
    }
end

return M
