local M = {}

function M.setup(configColors, configStyle)
    local newpaper = configColors
    local style    = configStyle

    return {
        ["@error.latex"]                          = { bg = newpaper.tex_error, sp = newpaper.error_fg, style = style.error },
        ["@character.special.latex"]              = { fg = newpaper.regexp_magenta, style = style.tex_o_style, nocombine = true },
        ["@character.special.ligatures.latex"]    = { fg = newpaper.tex_maroon, style = style.tex_o_style, nocombine = true },
        ["@character.special.math.latex"]         = { fg = newpaper.tex_math_cmd, style = style.tex_o_style, nocombine = true },
        ["@comment.verb.latex"]                   = { fg = newpaper.tex_verb, nocombine = true },
        ["@conceal.latex"]                        = { fg = newpaper.tex_math_cmd, nocombine = true },
        ["@function.latex"]                       = { fg = newpaper.tex_navy, nocombine = true },
        ["@function.bracket.latex"]               = { fg = newpaper.tex_navy, nocombine = true },
        ["@function.macro.latex"]                 = { fg = newpaper.tex_magenta, nocombine = true },
        ["@function.macro.cite.latex"]            = { fg = newpaper.tex_magenta_soft, nocombine = true },
        ["@function.math.latex"]                  = { fg = newpaper.tex_symbol, nocombine = true },
        ["@function.math.operator.latex"]         = { fg = newpaper.tex_operator, nocombine = true },
        ["@function.math.greek.latex"]            = { fg = newpaper.tex_math, nocombine = true },
        ["@function.math.trig.latex"]             = { fg = newpaper.tex_SI_green, nocombine = true },
        ["@function.math.markup.latex"]           = { fg = newpaper.tex_math_cmd, nocombine = true },
        ["@function.math.bracket.latex"]          = { fg = newpaper.tex_olive, nocombine = true },
        ["@keyword.directive.latex"]              = { fg = newpaper.tex_navy, style = style.tex_k_style, nocombine = true },
        ["@keyword.import.latex"]                 = { fg = newpaper.tex_blue, style = style.tex_k_style, nocombine = true },
        ["@keyword.import.verb.latex"]            = { fg = newpaper.tex_verb, style = style.tex_m_style, nocombine = true },
        ["@keyword.latex"]                        = { fg = newpaper.tex_keyword, style = style.tex_m_style, nocombine = true },
        ["@keyword.type.latex"]                   = { fg = newpaper.tex_blue, style = style.tex_m_style, nocombine = true },
        ["@keyword.type.section.latex"]           = { fg = newpaper.tex_aqua, style = style.tex_m_style, nocombine = true },
        ["@label.latex"]                          = { fg = newpaper.tex_darkorange, style = style.b_italic, nocombine = true },
        ["@label.math.latex"]                     = { fg = newpaper.tex_olive, nocombine = true },
        ["@markup.heading.1.latex"]               = { fg = newpaper.tex_navy, style = style.tex_m_style, nocombine = true },
        ["@markup.heading.2.latex"]               = { fg = newpaper.tex_part_title, style = style.tex_m_style, nocombine = true },
        ["@markup.heading.3.latex"]               = { link = "@markup.heading.2.latex" },
        ["@markup.heading.4.latex"]               = { link = "@markup.heading.2.latex" },
        ["@markup.heading.5.latex"]               = { link = "@markup.heading.2.latex" },
        ["@markup.heading.6.latex"]               = { link = "@markup.heading.2.latex" },
        ["@markup.link.url.latex"]                = { fg = newpaper.tex_navy, style = style.links, nocombine = true },
        ["@markup.math.inline.latex"]             = { fg = newpaper.tex_math, style = style.tex_z_style, nocombine = true },
        ["@module.latex"]                         = { fg = newpaper.tex_keyword, style = style.tex_k_style, nocombine = true },
        ["@number.float.latex"]                   = { fg = newpaper.tex_magenta, nocombine = true },
        ["@number.latex"]                         = { fg = newpaper.tex_red, nocombine = true },
        ["@operator.latex"]                       = { fg = newpaper.none },
        ["@operator.math.latex"]                  = { fg = newpaper.tex_operator, style = style.tex_o_style, nocombine = true },
        ["@operator.math.slash.latex"]            = { fg = newpaper.tex_operator, style = style.tex_br_style, nocombine = true },
        ["@operator.math.sub.latex"]              = { fg = newpaper.tex_pink, style = style.tex_o_style, nocombine = true },
        ["@punctuation.bracket.latex"]            = { fg = newpaper.tex_lightpurple, style = style.tex_br_style, nocombine = true },
        ["@punctuation.bracket.ref.latex"]        = { fg = newpaper.tex_lightgreen, style = style.tex_br_style, nocombine = true },
        ["@punctuation.bracket.cite.latex"]       = { fg = newpaper.tex_magenta_soft, style = style.tex_br_style, nocombine = true },
        ["@punctuation.bracket.math.latex"]       = { fg = newpaper.tex_operator, style = style.tex_br_style, nocombine = true },
        ["@punctuation.bracket.math.left.latex"]  = { fg = newpaper.tex_operator, style = style.tex_br_style, nocombine = true },
        ["@punctuation.bracket.math.right.latex"] = { fg = newpaper.tex_operator, style = style.tex_br_style, nocombine = true },
        ["@punctuation.bracket.math.sub.latex"]   = { fg = newpaper.tex_pink, style = style.tex_br_style, nocombine = true },
        ["@punctuation.dot.latex"]                = { fg = newpaper.tex_pink, style = style.d_style, nocombine = true },
        ["@punctuation.delimiter.symbol.latex"]   = { fg = newpaper.tex_lightpurple, style = style.tex_md_style, nocombine = true },
        ["@punctuation.delimiter.latex"]          = { fg = newpaper.tex_lightpurple, nocombine = true },
        ["@punctuation.special.latex"]            = { fg = newpaper.tex_string, nocombine = true },
        ["@punctuation.special.others.latex"]     = { fg = newpaper.regexp_blue, nocombine = true },
        ["@string.latex"]                         = { fg = newpaper.tex_teal, nocombine = true },
        ["@none.latex"]                           = { fg = newpaper.tex_string, style = style.s_style, nocombine = true },
        ["@none.comment.latex"]                   = { fg = newpaper.comments, nocombine = true },
        ["@none.accent.latex"]                    = { bg = newpaper.aqua },
        ["@none.fill.latex"]                      = { bg = newpaper.silver },
        ["@string.special.cyrmath.latex"]         = { fg = newpaper.tex_maroon, nocombine = true },
        ["@string.special.cyrtext.latex"]         = { fg = newpaper.tex_pink, style = style.s_style, nocombine = true },
        ["@string.special.unicodemath.latex"]     = { fg = newpaper.regexp_blue, nocombine = true },
        ["@string.special.unicodetext.latex"]     = { fg = newpaper.tex_math, style = style.s_style, nocombine = true },
        ["@type.latex"]                           = { fg = newpaper.tex_blue, style = style.tex_k_style, nocombine = true },
        ["@variable.parameter.latex"]             = { fg = newpaper.tex_orange, style = style.tex_a_style, nocombine = true },

        ["@constant.bibtex"]                      = { fg = newpaper.tex_math, nocombine = true },
        ["@function.builtin.bibtex"]              = { fg = newpaper.tex_maroon, nocombine = true },
        ["@keyword.bibtex"]                       = { fg = newpaper.tex_keyword, style = style.tex_k_style, nocombine = true },
        ["@number.bibtex"]                        = { fg = newpaper.tex_pink, nocombine = true },
        ["@operator.bibtex"]                      = { fg = newpaper.tex_operator, style = style.tex_o_style, nocombine = true },
        ["@punctuation.bracket.bibtex"]           = { fg = newpaper.tex_lightpurple, style = style.tex_br_style, nocombine = true },
        ["@punctuation.delimiter.bibtex"]         = { fg = newpaper.tex_orange, nocombine = true },
        ["@string.bibtex"]                        = { fg = newpaper.tex_teal, nocombine = true },
        ["@string.special.symbol.bibtex"]         = { fg = newpaper.tex_darkorange, nocombine = true },
        ["@variable.member.bibtex"]               = { fg = newpaper.tex_blue, nocombine = true },
        ["@variable.parameter.bibtex"]            = { fg = newpaper.tex_orange, nocombine = true },
    }
end

return M
