local M = {}

function M.setup(configColors, configStyle)

    -- stylua: ignore start

    local miniSyn  = {}
    miniSyn.colors = configColors
    miniSyn.style  = configStyle
    local newpaper = miniSyn.colors
    local style    = miniSyn.style

    miniSyn.loadPlugins = function()
        local plugins = {
            MiniAnimateCursor             = { reverse = true, nocombine = true },
            MiniAnimateNormalFloat        = { link = "NormalFloat" },
            MiniClueBorder                = { link = "FloatBorder" },
            MiniClueDescGroup             = { link = "DiagnosticFloatingWarn" },
            MiniClueDescSingle            = { link = "NormalFloat" },
            MiniClueNextKey               = { link = "DiagnosticFloatingHint" },
            MiniClueNextKeyWithPostkeys   = { link = "DiagnosticFloatingError" },
            MiniClueSeparator             = { link = "DiagnosticFloatingInfo" },
            MiniClueTitle                 = { link = "FloatTitle" },
            MiniCompletionActiveParameter = { style = style.underline },
            MiniCursorword                = { style = style.underline },
            MiniCursorwordCurrent         = { style = style.underline },
            MiniDepsChangeAdded           = { link = "diffAdded" },
            MiniDepsChangeRemoved         = { link = "diffRemoved" },
            MiniDepsHint                  = { link = "DiagnosticHint" },
            MiniDepsInfo                  = { link = "DiagnosticInfo" },
            MiniDepsMsgBreaking           = { link = "DiagnosticWarn" },
            MiniDepsPlaceholder           = { link = "Comment" },
            MiniDepsTitle                 = { link = "Title" },
            MiniDepsTitleError            = { link = "DiffDelete" },
            MiniDepsTitleSame             = { link = "DiffText" },
            MiniDepsTitleUpdate           = { link = "DiffAdd" },
            MiniDiffSignAdd               = { fg = newpaper.git_added },
            MiniDiffSignChange            = { fg = newpaper.git_modified },
            MiniDiffSignDelete            = { fg = newpaper.git_removed },
            MiniDiffOverAdd               = { link = "DiffAdd" },
            MiniDiffOverChange            = { link = "DiffText" },
            MiniDiffOverContext           = { link = "DiffChange" },
            MiniDiffOverDelete            = { link = "DiffDelete" },
            MiniFilesBorder               = { link = "FloatBorder" },
            MiniFilesBorderModified       = { link = "DiagnosticFloatingWarn" },
            MiniFilesCursorLine           = { link = "CursorLine" },
            MiniFilesDirectory            = { link = "Directory" },
            MiniFilesFile                 = { fg = newpaper.fg },
            MiniFilesNormal               = { link = "NormalFloat" },
            MiniFilesTitle                = { link = "FloatTitle" },
            MiniFilesTitleFocused         = { fg = newpaper.titles, style = style.b_bold },
            MiniHipatternsFixme           = { fg = newpaper.bg, bg = newpaper.todo_error, style = style.b_bold },
            MiniHipatternsHack            = { fg = newpaper.bg, bg = newpaper.todo_warn,  style = style.b_bold },
            MiniHipatternsNote            = { fg = newpaper.bg, bg = newpaper.todo_hint,  style = style.b_bold },
            MiniHipatternsTodo            = { fg = newpaper.bg, bg = newpaper.todo_info,  style = style.b_bold },
            MiniIconsAzure                = { fg = newpaper.lightblue },
            MiniIconsBlue                 = { fg = newpaper.blue },
            MiniIconsCyan                 = { fg = newpaper.lightmagenta },
            MiniIconsGreen                = { fg = newpaper.green },
            MiniIconsGrey                 = { fg = newpaper.grey },
            MiniIconsOrange               = { fg = newpaper.orange },
            MiniIconsPurple               = { fg = newpaper.purple },
            MiniIconsRed                  = { fg = newpaper.red },
            MiniIconsYellow               = { fg = newpaper.darkyellow },
            MiniIndentscopeSymbol         = { fg = newpaper.contextchar },
            MiniIndentscopePrefix         = { nocombine = true },
            MiniJump                      = { fg = newpaper.bg, bg = newpaper.accent },
            MiniJump2dDim                 = { link = "Comment" },
            MiniJump2dSpot                = { fg = newpaper.accent,    style = style.b_bold, nocombine = true },
            MiniJump2dSpotAhead           = { fg = newpaper.lightblue, bg = newpaper.bg,     nocombine = true },
            MiniJump2dSpotUnique          = { fg = newpaper.purple,    style = style.b_bold, nocombine = true },
            MiniMapNormal                 = { link = "NormalFloat" },
            MiniMapSymbolCount            = { fg = newpaper.purple },
            MiniMapSymbolLine             = { fg = newpaper.lightmagenta },
            MiniMapSymbolView             = { fg = newpaper.blue },
            MiniNotifyBorder              = { link = "FloatBorder" },
            MiniNotifyNormal              = { link = "NormalFloat" },
            MiniNotifyTitle               = { link = "FloatTitle" },
            MiniOperatorsExchangeFrom     = { link = "IncSearch" },
            MiniPickBorder                = { link = "FloatBorder" },
            MiniPickBorderBusy            = { fg = newpaper.warn_fg, bg = newpaper.float_bg, style = style.b_bold },
            MiniPickBorderText            = { link = "FloatTitle" },
            MiniPickIconDirectory         = { link = "Directory" },
            MiniPickIconFile              = { link = "MiniPickNormal" },
            MiniPickHeader                = { link = "Title" },
            MiniPickMatchCurrent          = { bg = newpaper.aqua },
            MiniPickMatchMarked           = { link = "Visual" },
            MiniPickMatchRanges           = { fg = newpaper.magenta, style = style.b_bold },
            MiniPickNormal                = { link = "NormalFloat" },
            MiniPickPreviewLine           = { bg = newpaper.aqua },
            MiniPickPreviewRegion         = { link = "IncSearch" },
            MiniPickPrompt                = { fg = newpaper.teal, bg = newpaper.bg },
            MiniStarterCurrent            = { nocombine = true },
            MiniStarterFooter             = { fg = newpaper.orange, style = style.b_italic },
            MiniStarterHeader             = { fg = newpaper.comments },
            MiniStarterInactive           = { link = "Comment" },
            MiniStarterItem               = { link = "Normal" },
            MiniStarterItemBullet         = { fg = newpaper.borders },
            MiniStarterItemPrefix         = { fg = newpaper.orange },
            MiniStarterSection            = { fg = newpaper.lightmagenta },
            MiniStarterQuery              = { fg = newpaper.lightblue },
            MiniStatuslineDevinfo         = { fg = newpaper.grey, bg = newpaper.silver },
            MiniStatuslineFileinfo        = { link = "MiniStatuslineDevinfo" },
            MiniStatuslineFilename        = { fg = newpaper.teal, bg = newpaper.silver },
            MiniStatuslineInactive        = { fg = newpaper.lightgrey, bg = newpaper.silver },
            MiniStatuslineModeCommand     = { fg = newpaper.bg, bg = newpaper.darkorange,   style = style.b_bold },
            MiniStatuslineModeInsert      = { fg = newpaper.bg, bg = newpaper.darkgreen,    style = style.b_bold },
            MiniStatuslineModeNormal      = { fg = newpaper.bg, bg = newpaper.teal,       style = style.b_bold },
            MiniStatuslineModeOther       = { fg = newpaper.bg, bg = newpaper.lightmagenta, style = style.b_bold },
            MiniStatuslineModeReplace     = { fg = newpaper.bg, bg = newpaper.magenta,      style = style.b_bold },
            MiniStatuslineModeVisual      = { fg = newpaper.bg, bg = newpaper.purple,       style = style.b_bold },
            MiniSurround                  = { link = "IncSearch" },
            MiniTablineCurrent            = { fg = newpaper.bg, bg = newpaper.accent, style = style.b_bold },
            MiniTablineFill               = { link = "TabLineFill" },
            MiniTablineHidden             = { fg = newpaper.fg,     bg = newpaper.bg },
            MiniTablineModifiedCurrent    = { fg = newpaper.accent, bg = newpaper.bg, style = style.b_bold },
            MiniTablineModifiedHidden     = { fg = newpaper.bg,     bg = newpaper.fg },
            MiniTablineModifiedVisible    = { fg = newpaper.accent, bg = newpaper.bg },
            MiniTablineTabpagesection     = { fg = newpaper.titles,  bg = newpaper.selection, style = style.b_bold },
            MiniTablineVisible            = { fg = newpaper.bg,     bg = newpaper.accent },
            MiniTestEmphasis              = { style = style.b_bold },
            MiniTestFail                  = { fg = newpaper.red,    style = style.b_bold },
            MiniTestPass                  = { fg = newpaper.darkgreen, style = style.b_bold },
            MiniTrailspace                = { fg = newpaper.disabled, bg = newpaper.pink },
        }
        return plugins
    end

    -- stylua: ignore end

    return miniSyn
end

return M
