local M = {}

function M.setup(configColors)
    local newpaper = configColors

    return {
        DevIconAi                  = { fg = newpaper.olive },
        DevIconAwk                 = { fg = newpaper.teal },
        DevIconBat                 = { fg = newpaper.green },
        DevIconBash                = { fg = newpaper.nephritis },
        DevIconBashProfile         = { fg = newpaper.nephritis },
        DevIconBashrc              = { fg = newpaper.nephritis },
        DevIconBrewfile            = { fg = newpaper.maroon },
        DevIconCoffee              = { fg = newpaper.olive },
        DevIconConfiguration       = { fg = newpaper.darkgrey },
        DevIconConfigRu            = { fg = newpaper.redorange },
        DevIconCrystal             = { fg = newpaper.fg },
        DevIconCsh                 = { fg = newpaper.grey },
        DevIconCson                = { fg = newpaper.olive },
        DevIconCsv                 = { fg = newpaper.darkengreen },
        DevIconCs                  = { fg = newpaper.green },
        DevIconCss                 = { fg = newpaper.purple },
        DevIconDb                  = { fg = newpaper.grey },
        DevIconDesktopEntry        = { fg = newpaper.purple },
        DevIconDiff                = { fg = newpaper.git_fg },
        DevIconDockerfile          = { fg = newpaper.tag_navy },
        DevIconDsStore             = { fg = newpaper.teal },
        DevIconDrools              = { fg = newpaper.redorange },
        DevIconDump                = { fg = newpaper.lightgrey },
        DevIconHaml                = { fg = newpaper.tag_navy },
        DevIconEjs                 = { fg = newpaper.olive },
        DevIconEnv                 = { fg = newpaper.orange },
        DevIconErb                 = { fg = newpaper.redorange },
        DevIconFennel              = { fg = newpaper.ocean },
        DevIconFish                = { fg = newpaper.grey },
        DevIconGemfile             = { fg = newpaper.redorange },
        DevIconGemspec             = { fg = newpaper.redorange },
        DevIconGitAttributes       = { fg = newpaper.git_fg },
        DevIconGitCommit           = { fg = newpaper.git_fg },
        DevIconGitConfig           = { fg = newpaper.git_fg },
        DevIconGitModules          = { fg = newpaper.git_fg },
        DevIconGitIgnore           = { fg = newpaper.git_fg },
        DevIconIco                 = { fg = newpaper.darkyellow },
        DevIconImportConfiguration = { fg = newpaper.darkgrey },
        DevIconJava                = { fg = newpaper.redorange },
        DevIconJs                  = { fg = newpaper.olive },
        DevIconJson                = { fg = newpaper.olive },
        DevIconKsh                 = { fg = newpaper.grey },
        DevIconLess                = { fg = newpaper.purple },
        DevIconLog                 = { fg = newpaper.fg },
        DevIconLua                 = { fg = newpaper.lua_navy },
        DevIconLuau                = { fg = newpaper.lua_navy },
        DevIconMd                  = { fg = newpaper.fg },
        DevIconMjs                 = { fg = newpaper.olive },
        DevIconNim                 = { fg = newpaper.darkyellow },
        DevIconOpenTypeFont        = { fg = newpaper.teal },
        DevIconPackageLockJson     = { fg = newpaper.maroon },
        DevIconPdf                 = { fg = newpaper.redorange },
        DevIconPrisma              = { fg = newpaper.fg },
        DevIconPy                  = { fg = newpaper.python_blue },
        DevIconPyc                 = { fg = newpaper.python_blue },
        DevIconPyd                 = { fg = newpaper.python_blue },
        DevIconPyo                 = { fg = newpaper.python_blue },
        DevIconRake                = { fg = newpaper.redorange },
        DevIconRakefile            = { fg = newpaper.redorange },
        DevIconRb                  = { fg = newpaper.redorange },
        DevIconRs                  = { fg = newpaper.rust_green },
        DevIconSql                 = { fg = newpaper.darkgrey },
        DevIconSh                  = { fg = newpaper.grey },
        DevIconScheme              = { fg = newpaper.fg },
        DevIconTxt                 = { fg = newpaper.tag_navy },
        DevIconTex                 = { fg = newpaper.tex_part_title },
        DevIconTextResource        = { fg = newpaper.olive },
        DevIconTypefont            = { fg = newpaper.teal },
        DevIconWebmanifest         = { fg = newpaper.tag_navy },
        DevIconZsh                 = { fg = newpaper.nephritis },
        DevIconZshenv              = { fg = newpaper.nephritis },
        DevIconZshProfile          = { fg = newpaper.nephritis },
        DevIconZshrc               = { fg = newpaper.nephritis },
    }
end

return M
